[OC-23]-create-userservice
JamshidS/online-quiz-application pull request #20
Opened 2023-12-21 18:22 UTC by eminecetin

2023-12-21 19:47 UTC, eycwave commented on src/main/java/com/quiz/service/QuizService.java
> +    String createUser(User user);
why did you write in QuizService 🤔

2023-12-26 14:31 UTC, JamshidS requested changes

2023-12-26 14:31 UTC, JamshidS commented on src/main/java/com/quiz/service/UserService.java
> +    User getUser(Long id) throws Exception;
`getUserById()`

2023-12-26 14:31 UTC, JamshidS commented on src/main/java/com/quiz/service/impl/UserServiceImpl.java
> +            return "Error creating user.";
```suggestion
            return "Error while creating user.";
```

2023-12-26 18:23 UTC, eycwave commented on src/main/java/com/quiz/service/impl/UserServiceImpl.java
> +        return userRepository.getUserById(id);
what if there is no user matching the given id number? so i guess you should add if condition.

2024-01-05 11:25 UTC, closed without merging