Tarik/oc 27 quiz question methods
JamshidS/online-quiz-application pull request #25
Opened 2023-12-25 12:40 UTC by TarikDemo

2023-12-25 12:43 UTC, eycwave commented on src/main/java/com/quiz/service/impl/QuizServiceImpl.java
> +    public void addQuizQuestion(Long quizId, String question) {
why did you write this in ServiceImpl class? isn't it exist in QuizQuestionRepository? can you explain thank you

2023-12-26 14:21 UTC, JamshidS requested changes

2023-12-26 14:21 UTC, JamshidS commented on src/main/java/com/quiz/service/QuizService.java
> +   void addQuizQuestion(Long quizId,String question);
return `String`

2023-12-26 14:21 UTC, JamshidS commented on src/main/java/com/quiz/service/QuizService.java
> +
create a new method that returns a  `List<QuizQuestion>`  with quizId;

2023-12-26 14:21 UTC, JamshidS commented on src/main/java/com/quiz/service/QuizService.java
> +   QuizQuestion getQuizQuestionByQuizId(Long listQuizId);
```suggestion
   QuizQuestion getQuizQuestionById(Long questionId);
```

2023-12-26 14:21 UTC, JamshidS commented on src/main/java/com/quiz/service/impl/QuizServiceImpl.java
> +        String query = "INSERT INTO quizquestion (uuid, quizId, question, createdDateTime) VALUES (?, ?, ?, ?)";
this is wrong just remove it.

2023-12-26 14:21 UTC, JamshidS commented on src/main/java/com/quiz/service/impl/QuizServiceImpl.java
> +    @Override
private final QuizQuestionRepository quizQuestionRepository;
// constructor injection. -> dependency injection

2023-12-29 11:14 UTC, JamshidS requested changes

2023-12-29 11:14 UTC, JamshidS commented on src/main/java/com/quiz/repository/QuizQuestionRepository.java
> +    public List<QuizQuestion> getAllQuizQuestion() {
```suggestion
    public List<QuizQuestion> getAllQuizQuestions() {
```

2023-12-29 11:14 UTC, JamshidS commented on src/main/java/com/quiz/service/impl/QuizServiceImpl.java
> +        return quizQuestionRepository.getAllQuizQuestion();
```suggestion
        return quizQuestionRepository.getAllQuizQuestions();
```

2023-12-29 11:19 UTC, JamshidS approved these changes

2024-01-02 14:02 UTC, merged