[OC-25] create user quiz methods
JamshidS/online-quiz-application pull request #36
Opened 2024-01-21 08:42 UTC by furkanErenoglu

2024-01-21 09:01 UTC, furkanErenoglu commented on src/main/java/com/quiz/service/impl/UserQuizServiceImpl.java
> +    public String takeQuiz(long userId, int quizId) {
This branch and my local computer are not the same, I will solve the problem as soon as possible.

2024-01-23 14:09 UTC, JamshidS requested changes

2024-01-23 14:09 UTC, JamshidS commented on src/main/java/com/quiz/service/impl/ResultServiceImpl.java
> +
`Result getResultByUserUUID(String uuid);`

2024-01-30 14:25 UTC, JamshidS requested changes

2024-01-30 14:25 UTC, JamshidS commented on src/main/java/com/quiz/service/ResultService.java
> +public interface ResultService {
delete this once the Yalcin's PR is merged

2024-02-02 11:11 UTC, closed without merging